# Form implementation generated from reading ui file 'c:\Users\WB-wangyu\Desktop\文档\开发文档\DrainageTube\view\homepage.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt6.QtCore import Qt
from PyQt6.QtGui import QFont
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QWidget, QApplication, QTableWidgetItem, QPushButton, QCheckBox, QMessageBox

from listAdd.yinliu_addList import AddItemList
from listAdd.yinliu_editList import EditItemList
from signal_update.signalsUpdate import global_signals
from dao import listDao
from listView.yinliu_viewList import ViewList


class main_widget(QWidget):

    def __init__(self):
        super(main_widget, self).__init__()
        self.setWindowFlag(QtCore.Qt.WindowType.MSWindowsFixedSizeDialogHint)
        self.setupUi(self)
        self.total_pages = 1  # 初始化总页数为1
        self.rows_per_page = 10
        self.now_page = 1
        self.fake_data = None
        self.initTable()
        global_signals.updateTable.connect(self.initTable)

    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(1000, 700)
        self.label = QtWidgets.QLabel(parent=widget)
        self.label.setGeometry(QtCore.QRect(40, 10, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 50, 911, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nameSearchLine = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        self.nameSearchLine.setTabletTracking(False)
        self.nameSearchLine.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.nameSearchLine.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.nameSearchLine.setToolTip("")
        self.nameSearchLine.setAccessibleDescription("")
        self.nameSearchLine.setStyleSheet("")
        self.nameSearchLine.setInputMask("")
        self.nameSearchLine.setObjectName("nameSearchLine")
        self.horizontalLayout.addWidget(self.nameSearchLine)
        self.nameSearchButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.nameSearchButton.setObjectName("nameSearchButton")
        self.horizontalLayout.addWidget(self.nameSearchButton)

        # 绑定搜索按钮点击事件
        self.nameSearchButton.clicked.connect(self.initTable)

        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.addButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)

        # 新增按钮点击事件
        self.addButton.clicked.connect(self.open_addList_window)

        self.importButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.importButton.setObjectName("importButton")
        self.horizontalLayout.addWidget(self.importButton)
        self.deleteButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout.addWidget(self.deleteButton)

        # 添加删除按钮点击事件
        self.deleteButton.clicked.connect(self.batchDeleteButtonClicked)

        self.downloadButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.downloadButton.setObjectName("downloadButton")
        self.horizontalLayout.addWidget(self.downloadButton)
        self.materialTable = QtWidgets.QTableWidget(parent=widget)
        self.materialTable.setGeometry(QtCore.QRect(40, 140, 911, 451))
        self.materialTable.setObjectName("materialTable")
        self.materialTable.setColumnCount(0)
        self.materialTable.setRowCount(0)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(parent=widget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(40, 600, 911, 80))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.materialButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_3)
        self.materialButton.setObjectName("materialButton")
        self.horizontalLayout_3.addWidget(self.materialButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pageComboBox = QtWidgets.QComboBox(parent=self.horizontalLayoutWidget_3)
        self.pageComboBox.setObjectName("pageComboBox")
        self.pageComboBox.addItem("")
        self.pageComboBox.addItem("")
        self.pageComboBox.addItem("")
        self.pageComboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.pageComboBox)
        self.pageLabel = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_3)
        self.pageLabel.setObjectName("pageLabel")
        self.horizontalLayout_3.addWidget(self.pageLabel)
        self.forwardButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_3)
        self.forwardButton.setObjectName("forwardButton")
        self.horizontalLayout_3.addWidget(self.forwardButton)

        # 添加前一页按钮点击事件
        self.forwardButton.clicked.connect(self.backwardButtonClicked)

        self.backwardButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_3)
        self.backwardButton.setObjectName("backwardButton")
        self.horizontalLayout_3.addWidget(self.backwardButton)

        # 添加后一页按钮点击事件
        self.backwardButton.clicked.connect(self.forwardButtonClicked)

        self.pageInpuLine = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_3)
        self.pageInpuLine.setObjectName("pageInpuLine")
        self.horizontalLayout_3.addWidget(self.pageInpuLine)
        self.goToButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_3)
        self.goToButton.setObjectName("goToButton")
        self.horizontalLayout_3.addWidget(self.goToButton)

        # 新增前往按钮点击事件
        self.goToButton.clicked.connect(self.goToButtonClicked)

        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    # 新增按钮点击打开窗口
    def open_addList_window(self):
        self.add_list_window = AddItemList()
        self.add_list_window.show()

    def open_editList_window(self, row_id):
        self.edit_list_window = EditItemList(row_id)
        self.edit_list_window.show()

    def open_checkList_window(self, row_id):
        self.check_list_window = ViewList(row_id)
        self.check_list_window.show()

    # 新增下拉框选择显示数据量
    def pageComboBoxChanged(self, index):
        """
        Handle the change in the pageComboBox
        :param index: Index of the selected item in the pageComboBox
        """
        rows_per_page_options = [10, 20, 50, 100]  # Define the available rows per page options
        self.rows_per_page = rows_per_page_options[index]  # Get the selected rows per page value

        # Reinitialize the table based on the selected rows per page
        self.now_page = 1
        self.pageInpuLine.setText("")
        self.initTable()

    def backwardButtonClicked(self):
        if self.now_page > 1:  # 如果当前页不是第一页
            self.now_page -= 1  # 更新当前页数为上一页
            self.pageLabel.setText(f"第{self.now_page}页/共{self.total_pages}页")  # 更新页面标签显示
            start_row = (self.now_page - 1) * self.rows_per_page  # 计算起始行
            end_row = self.now_page * self.rows_per_page  # 计算结束行
            self.clearTableExceptHeader()  # 清空表格数据
            self.showPage(start_row, end_row)  # 显示上一页的数据
        # 如果当前页已经是第一页，则点击按钮时不执行任何操作
            
    def forwardButtonClicked(self):
        if self.now_page < self.total_pages:  # 如果当前页不是最后一页
            self.now_page += 1  # 更新当前页数为下一页
            self.pageLabel.setText(f"第{self.now_page}页/共{self.total_pages}页")  # 更新页面标签显示
            start_row = (self.now_page - 1) * self.rows_per_page  # 计算起始行
            end_row = min(self.now_page * self.rows_per_page, len(self.fake_data))  # 计算结束行
            self.clearTableExceptHeader()  # 清空表格数据
            self.showPage(start_row, end_row)  # 显示下一页的数据
        # 如果当前页已经是最后一页，则点击按钮时不执行任何操作


    def goToButtonClicked(self):
        # Get the input page number
        page_text = self.pageInpuLine.text()
        if page_text.isdigit():  # Check if the input is a number
            page_number = int(page_text)

            if 1 <= page_number <= self.total_pages:
                # Calculate the start and end rows for the specified page
                start_row = (page_number - 1) * self.rows_per_page
                end_row = min(page_number * self.rows_per_page, len(self.fake_data))

                self.now_page = page_number
                self.pageLabel.setText(f"第{self.now_page}页/共{self.total_pages}页")

                # Clear the table except for the header row before displaying the new data
                self.clearTableExceptHeader()

                # Display the data for the specified page
                self.showPage(start_row, end_row)
            else:
                QMessageBox.warning(None, '系统提示', '超出页面范围！')
        else:
            QMessageBox.warning(None, '系统提示', '请输入数字！')

    def clearTableExceptHeader(self):
        self.materialTable.clearContents()
        self.materialTable.setRowCount(0)

    def showPage(self, start_row, end_row):

        rows = self.rows_per_page
        columns = 9

        self.materialTable.setRowCount(rows+1) 
        self.materialTable.setColumnCount(columns)
        self.materialTable.verticalHeader().setVisible(False)  # 隐藏垂直标题 序号

        self.master_checkbox = QCheckBox()  # 将 master_checkbox 存储为对象的属性
        self.master_checkbox.setStyleSheet("QCheckBox { padding-left: 10%; text-align: center;}")
        self.master_checkbox.stateChanged.connect(self.master_checkbox_changed)

        self.materialTable.setCellWidget(0, 0, self.master_checkbox)  # 使用 self.master_checkbox

        # 设置居中和加粗的字体
        font = QFont()
        font.setBold(True)
        column_names = ["序号", "名称", "文件编号", "版本号", "产品规格", "物料编码"]
        for col, text in enumerate(column_names, start=1):
            item = QTableWidgetItem(text)
            item.setFont(font)  # 设置字体为加粗
            item.setTextAlignment(Qt.AlignmentFlag.AlignCenter)  # 设置居中对齐
            item.setFlags(Qt.ItemFlag.ItemIsEnabled)  # 设置单元格为只读
            self.materialTable.setItem(0, col, item)

        for col in range(columns-2, columns):
            item = QTableWidgetItem("")
            item.setFlags(Qt.ItemFlag.ItemIsEnabled)  # Set the cells to read-only
            self.materialTable.setItem(0, col, item)
        
        # 隐藏原始的列名
        self.materialTable.horizontalHeader().setVisible(False)

        rows = min(self.rows_per_page, end_row-start_row)

        for row in range(1, rows+1):  # 从第二行开始，添加序号
            item = QTableWidgetItem(str((self.now_page-1)*self.rows_per_page + row))  # 将行号作为文本创建一个表格项
            item.setTextAlignment(Qt.AlignmentFlag.AlignCenter)  # 设置居中对齐
            item.setFlags(Qt.ItemFlag.ItemIsEnabled)  # 设置单元格为只读
            self.materialTable.setItem(row, 1, item)  # 将表格项添加到第二列

        for row in range(1, self.rows_per_page + 1):  # 从第二行开始，添加数据
            if row <= rows:
                # 显示的行
                for col in range(2, columns - 2):  # 从第三列开始
                    item = QTableWidgetItem(str(self.fake_data[row + start_row - 1][col - 1]))  # 调整索引以匹配 fake_data 列表
                    item.setTextAlignment(Qt.AlignmentFlag.AlignCenter)  # 设置居中对齐
                    item.setFlags(Qt.ItemFlag.ItemIsEnabled)  # 设置单元格为只读
                    self.materialTable.setItem(row, col, item)  # 在表格中设置项目
            else:
                # 未显示的行
                for col in range(0, columns):
                    item = QTableWidgetItem("")  # 创建空项目
                    item.setFlags(Qt.ItemFlag.ItemIsEnabled)  # 设置单元格为只读
                    self.materialTable.setItem(row, col, item)  # 在表格中设置项目


        # 在最后两列添加按钮
        for row in range(rows):
            checkbox = QCheckBox()  # 创建复选框
            checkbox.setStyleSheet("QCheckBox { padding-left: 10%; text-align: center;}")
            self.materialTable.setCellWidget(row+1, 0, checkbox)  # 将复选框添加到表格的第一列
            self.edit_button = QPushButton("编辑")
            self.materialTable.setCellWidget(row+1, columns-2, self.edit_button)  # 将编辑按钮添加到表格的最后一列

            # 获取当前数据的id
            row_id = self.fake_data[(self.now_page - 1) * self.rows_per_page + row][0]
            # print(row_id)
            # print(row_id)

            # 添加编辑按钮点击事件
            self.edit_button.clicked.connect(lambda _, id=row_id: self.open_editList_window(id))

            self.check_button = QPushButton("查看")  # 创建查看按钮
            self.materialTable.setCellWidget(row+1, columns-1, self.check_button)  # 将查看按钮添加到表格的最后一列
            # 添加查看按钮点击事件
            self.check_button.clicked.connect(lambda _, id=row_id: self.open_checkList_window(id))
        
        self.materialTable.setColumnWidth(0, 30)  # Adjust the width of the "Edit" button column
        self.materialTable.setColumnWidth(1, 40)  # Adjust the width of the "Save" button column
        self.materialTable.setColumnWidth(2, 150)  # Adjust the width of the "View" button column
        self.materialTable.setColumnWidth(3, 150)  # Adjust the width of the "Edit" button column
        self.materialTable.setColumnWidth(4, 140)  # Adjust the width of the "Save" button column
        self.materialTable.setColumnWidth(5, 150)  # Adjust the width of the "View" button column
        self.materialTable.setColumnWidth(6, 150)  # Adjust the width of the "Edit" button column
        self.materialTable.setColumnWidth(7, 45)  # Adjust the width of the "Save" button column
        self.materialTable.setColumnWidth(8, 45)  # Adjust the width of the "View" button column
        
        for row in range(self.rows_per_page+1):
            self.materialTable.setRowHeight(row,40)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Homepage"))
        self.label.setText(_translate("widget", "首页"))
        self.nameSearchLine.setPlaceholderText(_translate("widget", "要查询的名称"))
        self.nameSearchButton.setText(_translate("widget", "查询"))
        self.addButton.setText(_translate("widget", "新增"))
        self.importButton.setText(_translate("widget", "导入"))
        self.deleteButton.setText(_translate("widget", "批量删除"))
        self.downloadButton.setText(_translate("widget", "批量下载"))
        self.materialButton.setText(_translate("widget", "物料库"))
        self.pageComboBox.setItemText(0, _translate("widget", "每页10条"))
        self.pageComboBox.setItemText(1, _translate("widget", "每页20条"))
        self.pageComboBox.setItemText(2, _translate("widget", "每页50条"))
        self.pageComboBox.setItemText(3, _translate("widget", "每页100条"))
        self.pageLabel.setText(_translate("widget", "第1页/共5页"))
        self.forwardButton.setText(_translate("widget", "前一页"))
        self.backwardButton.setText(_translate("widget", "后一页"))
        self.pageInpuLine.setPlaceholderText(_translate("widget", "请输入页数"))
        self.goToButton.setText(_translate("widget", "前往"))

        self.pageComboBox.currentIndexChanged.connect(self.pageComboBoxChanged)

    def master_checkbox_changed(self, state):
        if self.now_page != 1:
            length_page = len(self.fake_data) - (self.now_page - 1) * self.rows_per_page
            rows = min(self.rows_per_page, length_page)
        else:
            rows = min(self.rows_per_page, len(self.fake_data))
        for row in range(1, rows+1):  # 从第二行开始
            checkbox = self.materialTable.cellWidget(row, 0)  # 获取复选框
            if state == 2:
                checkbox.setCheckState(Qt.CheckState.Checked)  # 设置为选中状态
            else:
                checkbox.setCheckState(Qt.CheckState.Unchecked)  # 设置为未选中状态
                
    def batchDeleteButtonClicked(self):
        selected_rows = []  # 存储选中的行的数据
        max_row = min(self.rows_per_page, len(self.fake_data) - (self.now_page - 1) * self.rows_per_page)  # 获取当前页的实际数据量
        for row in range(1, max_row + 1):  # 从第二行开始遍历表格的每一行
            checkbox = self.materialTable.cellWidget(row, 0)  # 获取复选框
            if checkbox and checkbox.isChecked():  # 如果复选框存在且被选中
                # 获取选中行的 id
                selected_id = self.fake_data[(self.now_page - 1) * self.rows_per_page + row - 1][0]
                selected_rows.append(selected_id)  # 将选中行的 id 添加到列表中

        if len(selected_rows) == 0:
             QMessageBox.warning(None, '系统提示', '请选中您需要删除的那行记录！')
             return
        
        reply = QMessageBox.question(self, '系统提示', '您确定要删除这条记录吗？',
                                     QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No,
                                     QMessageBox.StandardButton.No)
        if reply == QMessageBox.StandardButton.Yes:
            if listDao.delete(selected_rows) > 0:
                QMessageBox.information(None, '系统提示', '删除成功')
                self.initTable()
            else:
                QMessageBox.warning(None, '系统提示', '删除失败')

    def initTable(self):
        """
        根据条件初始化表格
        :return:
        """
        # print("initTable")
        self.clearTableExceptHeader()
        s_Name = self.nameSearchLine.text()

        result = listDao.list(s_Name)

        if result:
            self.fake_data = result

        self.total_pages = (len(self.fake_data) + self.rows_per_page - 1) // self.rows_per_page

        # Check if the current page exceeds the total pages after the data deletion
        if self.now_page > self.total_pages:
            self.now_page = max(1, self.total_pages)  # Update the current page to the last page or the first page
            self.pageLabel.setText(f"第{self.now_page}页/共{self.total_pages}页")
        else:
            self.pageLabel.setText(f"第{self.now_page}页/共{self.total_pages}页")

        start_row = (self.now_page - 1) * self.rows_per_page
        end_row = min(self.now_page * self.rows_per_page, len(self.fake_data))

        self.showPage(start_row, end_row)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    ui = main_widget()
    ui.show()

    sys.exit(app.exec())